/* 用户可见术语的唯一来源（window.StudyTerms）。
 *
 * 所有视图从这里取文案：视图里不得再散落同义词硬编码。
 * 术语取值与 `docs/skills/L0/glossary.md`、`docs/superpowers/specs/2026-09-17-glossary.md`
 * 对齐；字面量一旦被门禁断言（例如证据栏检索模式行）就是契约，改动需同步门禁。
 */
(function () {
  "use strict";

  const terms = {
    app: {
      name: "学习工作台",
      brandMark: "学",
      loading: "正在打开学习空间",
      refreshing: "刷新工作区",
      refresh: "刷新",
      reload: "重新载入工作区",
      logout: "退出",
      logoutFull: "退出登录",
      settings: "设置",
      settingsDescription: "账号、主题与工作区说明",
      close: "关闭",
      themeTitle: "星空主题",
      themeNote:
        "深空底 + 青色/紫色霓虹描边，玻璃拟态面板用于分隔模块。已适配 prefers-reduced-motion：系统要求减少动态时星空静止。",
      accountTitle: "账号信息",
    },
    auth: {
      tagline: "把下一步学什么，变成今天能完成的事",
      passwordCopy: "使用用户名和密码进入学习空间。",
      modeLabel: "认证方式",
      modes: { login: "密码登录", register: "注册账号" },
      usernameLabel: "用户名",
      usernamePlaceholder: "1–16 个字符",
      passwordLabel: "密码",
      passwordPlaceholder: "请输入密码",
      passwordPlaceholderRegister: "6-12 个字符",
      passwordHint: "密码长度需为 6-12 个字符。",
      enter: "进入学习空间",
      entering: "正在进入…",
      createAccount: "创建账号",
      login: "登录",
      submitting: "处理中…",
    },
    projects: {
      heading: "项目",
      empty: "还没有项目",
      createSummary: "新建项目",
      nameLabel: "项目名称",
      namePlaceholder: "例如：Agent 工程基础",
      goalLabel: "项目目标（可选）",
      goalPlaceholder: "项目目标（可选）",
      create: "+ 创建项目",
      created: "项目已创建",
      emptyTitle: "先创建一个学习项目",
      emptyCopy: "项目会保存你的会话、资料和计划。",
      emptyAction: "创建项目",
      listLabel: "学习项目",
    },
    workspace: {
      eyebrowProject: "当前项目",
      eyebrowSpace: "学习空间",
      pickProject: "选择一个项目",
      noGoal: "还没有写下项目目标",
      newConversationLabel: "新会话名称",
      newConversationPlaceholder: "新会话名称",
      newConversation: "+ 新会话",
      conversationCreated: "会话已创建",
    },
    tabs: { label: "项目视图", conversation: "会话", plan: "计划", sources: "资料" },
    conversation: {
      pickerLabel: "会话",
      unnamed: "未命名会话",
      noneTitle: "还没有会话",
      noneCopy: "创建一个会话后开始提问。",
      startTitle: "从一个问题开始",
      startCopy: "你的提问和回答会按时间顺序保存在这里。",
      inputLabel: "输入问题",
      inputPlaceholder: "你现在想弄懂什么？",
      inputHint: "回答会基于当前项目资料",
      send: "发送问题",
      sending: "处理中…",
      answerReady: "回答已准备好",
      polling: "连接暂时中断，正在继续查询回答进度",
      pollTimeout: "运行仍在处理中，刷新工作区即可继续查看",
    },
    messages: { you: "你", assistant: "学习助手", system: "系统" },
    run: { queued: "排队中", running: "生成中", succeeded: "已完成", failed: "失败", reconciliation_required: "待对账" },
    plan: {
      eyebrow: "学习路径",
      version: (version) => `第 ${version || 1} 版计划`,
      none: "还没有计划",
      goalLabel: "学习目标",
      goalPlaceholder: "完成后你希望能独立做什么？",
      milestoneLabel: "第一个里程碑",
      milestonePlaceholder: "例如：能解释 Agent harness 的关键边界",
      create: "创建计划",
      creating: "创建中…",
      manualTitle: "手工创建计划",
      readOnlyNote: "当前计划为只读版本；后续编辑会保留任务身份和学习证据。",
      generatedNote: "计划由诊断生成：任务可流转并提交学习反馈，学习证据由服务端裁决。",
      generatedVersion: "生成版本",
      generate: "生成学习计划",
      regenerate: "生成新计划（替换当前计划）",
      generating: "生成中…",
      generateNeedsDiagnosis: "请先完成基础诊断，再生成学习计划",
      generateRequired: "生成新计划必须显式触发，不会静默覆盖当前计划。",
      generated: "学习计划已生成",
      generateReady: "可以按诊断生成计划",
      milestones: "里程碑",
      tasks: "任务",
    },
    diagnosis: {
      title: "基础诊断",
      copy: "用三个问题告诉平台你的起点，生成计划时按它选择任务节奏。",
      experienceLabel: "已有基础",
      hoursLabel: "每周可投入小时数",
      styleLabel: "偏好学习方式",
      levels: { beginner: "初学", familiar: "有一些基础", experienced: "已有实践经验" },
      styles: { reading: "阅读", practice: "动手实践", mixed: "混合方式" },
      submit: "保存诊断",
      submitting: "保存中…",
      done: "基础诊断已完成",
      summary: "诊断结论",
      hoursSuffix: "小时/周",
      required: "请先完成基础诊断",
      saved: "基础诊断已保存",
    },
    tasks: {
      status: { pending: "待开始", in_progress: "进行中", done: "已完成", skipped: "已跳过" },
      statusLabel: "任务状态",
      objective: "学习目标",
      instruction: "怎么做",
      deliverable: "要交出的东西",
      acceptance: "完成标准",
      estimated: "预计用时",
      minutes: (value) => `${value} 分钟`,
      type: "任务类型",
      verified: "已验证",
      unverified: "未验证",
      start: "开始任务",
      complete: "标记完成",
      started: "任务已开始",
      completed: "任务已完成",
      transitioning: "更新中…",
      readOnly: "手工计划任务保持只读，不会写入学习证据。",
    },
    submission: {
      title: "提交学习反馈",
      label: "写下你的完成情况",
      placeholder: "用你自己的话说明做了什么、结果如何。",
      submit: "提交反馈",
      submitting: "提交中…",
      cancel: "收起",
      selfReport: "自报反馈",
      // 关键诚实标注：自报只被记录，不能等同于被验证。
      selfReportNotice: "已记录，不等于自动评分。自报反馈只作为低观测强度证据留档，是否「已验证」由服务端证据聚合决定。",
      recorded: "学习反馈已记录",
      empty: "还没有提交反馈",
      listTitle: "已提交反馈",
    },
    sources: {
      eyebrow: "项目资料",
      count: (total) => `${total} 份资料`,
      searchLabel: "搜索公开资料",
      searchPlaceholder: "输入主题或关键词",
      search: "搜索",
      searching: "搜索中…",
      candidateUrlLabel: "资料网址",
      candidateUrlPlaceholder: "https://example.com/guide",
      candidateTitleLabel: "候选标题",
      candidateTitlePlaceholder: "例如：事务入门指南",
      candidateSnippetLabel: "摘要（可选）",
      candidateSnippetPlaceholder: "帮助你确认来源，不会代替正文",
      registerCandidate: "登记候选资料",
      registering: "登记中…",
      confirmDownload: "确认下载",
      candidateAdded: "候选资料已登记，请确认后下载",
      noCandidatesTitle: "还没有候选资料",
      noCandidatesCopy: "粘贴一个公开网址，确认后才会进入下载队列。",
      uploadedTitle: "上传本地资料",
      displayLabel: "资料名称",
      displayPlaceholder: "例如：Agent 设计笔记",
      docTitleLabel: "文档标题",
      docTitlePlaceholder: "例如：工具调用边界",
      contentLabel: "正文",
      contentPlaceholder: "粘贴 Markdown 或纯文本",
      register: "登记资料",
      registered: "资料已登记，正在处理",
      untyped: "未标注类型",
      version: (documentId) => `版本 ${documentId}`,
      ingestion: { queued: "排队中", processing: "处理中", succeeded: "已处理", failed: "处理失败", registered: "已登记" },
      acquisition: {
        queued: "等待下载",
        running: "下载中",
        succeeded: "已下载",
        failed: "下载失败",
        unknown: "待确认",
        selected: "已授权",
        pending: "待确认",
      },
      queuedNotice: "资料已加入下载队列",
      found: (total) => `找到 ${total} 条候选资料，请确认后下载`,
      noneFound: "没有找到可用资料候选",
      emptyTitle: "还没有资料",
      emptyCopy: "登记资料后，回答可以带上原文引用。",
    },
    library: {
      title: "知识库",
      subtitle: "用户级资料库，跨项目共享；关联后才进入当前项目",
      railLabel: "知识库资料",
      loading: "正在加载知识库…",
      count: (total) => `${total} 份库资料`,
      emptyTitle: "知识库还没有资料",
      emptyCopy: "添加一份资料后，可以关联到任意学习项目。",
      addTitle: "添加库资料",
      nameLabel: "条目名称",
      namePlaceholder: "例如：事务入门指南",
      urlLabel: "来源网址（可选）",
      urlPlaceholder: "https://example.com/guide",
      contentLabel: "粘贴文本（可选）",
      contentPlaceholder: "粘贴 Markdown 或纯文本",
      add: "添加到知识库",
      adding: "添加中…",
      added: "库资料已添加",
      refresh: "刷新知识库",
      attach: "关联到当前项目",
      attaching: "关联中…",
      attached: "已关联到当前项目",
      alreadyAttached: "该资料已在当前项目",
      noProject: "先选择一个项目，才能关联库资料",
      hasContent: "已有正文",
      noContent: "缺少正文",
      registeredAt: "登记时间",
      acquisitionUrl: "来自网址",
      acquisitionText: "来自粘贴文本",
      errorTitle: "知识库暂时不可用",
      invalidName: "请填写资料名称",
      invalidInput: "网址和粘贴文本至少填一个",
    },
    evidence: {
      title: "证据",
      sourcesTitle: "资料状态",
      runStatus: "运行状态",
      verified: "来源已核验",
      general: "一般性回答（未核验来源）",
      reconciliation: "需要对账",
      groundingSourced: "回答含有已核验来源",
      groundingUnsourced: "回答没有通过核验的来源",
      emptyCitations: "完成回答后，已核验的引用会出现在这里。",
      emptyRailRegistered: (total) => `${total} 份资料已登记，等待回答引用。`,
      emptyRailPlan: "先登记资料，回答才有可回读的证据。",
      emptyRailSelect: "选择一个项目开始。",
      span: (start, end) => `第 ${start}–${end} 字`,
      read: "读取原文",
      reading: "读取中…",
    },
    retrieval: {
      keyword: "关键词检索",
      hybrid: "混合检索（关键词 + 向量）",
      degraded: (reason) => `向量检索不可用，已回退关键词检索（${reason}）`,
      reasons: {
        embedding_provider_failed: "向量服务不可用",
        vector_index_unavailable: "向量索引未就绪",
        embedding_model_version_mismatch: "向量模型版本不一致",
      },
      unknownReason: "检索组件异常",
    },
    routing: {
      applied: "本地查询改写 · 云端教学回答",
      fallback: "查询改写不可用 · 云端教学回答",
      disabled: "云端教学回答",
    },
    notices: {
      unknownResult: (label) => `${label}结果未知，请确认后重试。`,
      retrySame: "用同一请求重试",
      retrying: "重试中…",
      closeError: "关闭错误",
      refreshed: "已刷新",
      projectCreated: "项目已创建",
    },
    commands: {
      createProject: "创建项目",
      createConversation: "创建会话",
      sendQuestion: "发送问题",
      createPlan: "创建计划",
      registerSource: "登记资料",
      uploadSource: "上传资料正文",
      registerCandidate: "登记候选资料",
      sourceSearch: "搜索资料",
      selectCandidate: "开始下载资料",
      saveDiagnosis: "保存诊断",
      generatePlan: "生成学习计划",
      transitionTask: "更新任务状态",
      submitTask: "提交学习反馈",
      addLibrarySource: "添加库资料",
      attachLibrarySource: "关联库资料",
    },
    errors: {
      network: "网络连接失败，请稍后重试",
      byCode: {
        TEACHING_PROVIDER_DISABLED: "教学服务尚未启用",
        RECONCILIATION_REQUIRED: "这次请求的结果待对账，暂时不能自动重试",
        BUDGET_EXCEEDED: "项目预算不足，请减少资料或稍后再试",
        CSRF_DENIED: "页面来源校验失败，请刷新后重试",
        already_authenticated: "当前浏览器已有会话，请先退出后再切换账号",
        USERNAME_TAKEN: "用户名已注册，请换一个用户名",
        REGISTRATION_DISABLED: "注册暂未开放",
        PASSWORD_LOGIN_DISABLED: "密码登录暂未启用",
        EVIDENCE_UNMAPPED: "该任务没有对应的能力映射，无法写入学习证据",
        PARAMS_INVALID: "请先完成基础诊断，再生成学习计划",
      },
      unauthorized: "用户名或密码错误，或会话已失效",
      fallback: (status) => `请求失败（${status}）`,
      close: "关闭",
    },
  };

  window.StudyTerms = terms;
})();