"""核心表与 RLS 策略

第一份迁移。它同时做三件事，**第三件不能省**：

1. 建立核心表：租户 / 主体 / 项目 / 项目授权 / 确认记录 / 证据事件 / 执行意图；
2. 为每张租户表启用 **FORCE ROW LEVEL SECURITY**，策略基于会话变量
   `app.tenant_id`（项目级表同时要求 `app.project_id`）；
3. **收紧应用角色的权限** —— 表 owner 是迁移角色，`study_app` 只拿到 DML，
   且对 `evidence_events` 只有 `SELECT` / `INSERT`。

第 3 条的意义：append-only 由**权限系统**保证，而不是靠代码自觉。
代码可能写错、可能有人图方便加一条 UPDATE；GRANT 不会。

## 为什么「缺上下文」必须变成零行

策略写成 `tenant_id = current_setting('app.tenant_id', true)`。
第二个参数 `true` 表示"变量未设置时返回 NULL 而非报错"，而
`tenant_id = NULL` 恒为 false —— 于是「忘记设置租户上下文」自然退化成
「什么都查不到」，而不是「查到全部」。

这与"应用层记得加 where 条件"是两种完全不同的保障：
前者由数据库执行，**忘记就失败**；后者依赖每个查询都写对，**漏一个就泄露**。
不变量 #2 靠的是前者。

## 应用角色必须先存在

迁移**不会**创建 `study_app`，因为那需要把密码写进迁移文件 ——
密码属于密钥，不能进仓库（项目红线）。角色由运维脚本创建：

    scripts\\sql\\create_app_role.sql

角色不存在时本迁移会**显式失败**，而不是跳过 GRANT（跳过就意味着
"看起来迁移成功了，其实应用角色什么都没权限"）。
"""

from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

APP_ROLE = "study_app"


def _rls_statements(table: str, *, project_scoped: bool = False) -> list[str]:
    """生成一张租户表的 RLS 语句。

    项目级表额外要求 `app.project_id` 匹配 —— 多收窄一层，
    让「拿着 A 项目的上下文去读 B 项目的确认」也走不通，
    而不只是"同一个租户内随便读"。
    """
    predicate = "tenant_id = current_setting('app.tenant_id', true)"
    if project_scoped:
        predicate = (
            f"({predicate})\n"
            f"       AND project_id = current_setting('app.project_id', true)"
        )
    return [
        f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
        f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY",
        f"DROP POLICY IF EXISTS {table}_isolation ON {table}",
        f"CREATE POLICY {table}_isolation ON {table}\n"
        f"    USING ({predicate})\n"
        f"    WITH CHECK ({predicate})",
    ]


TABLES: list[str] = [
    "tenants",
    "principals",
    "projects",
    "project_grants",
    "confirmations",
    "evidence_events",
    "action_intents",
]

# 项目级表：读写的上下文必须同时含 tenant 与 project。
PROJECT_SCOPED = {"confirmations", "evidence_events", "action_intents"}

# append-only 的表只给 SELECT / INSERT。
APPEND_ONLY = {"evidence_events"}


def _assert_app_role_exists() -> None:
    """角色不存在就显式报错。"""
    op.execute(
        f"""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
        RAISE EXCEPTION 'role {APP_ROLE} does not exist; '
            'create it first with scripts/sql/create_app_role.sql';
    END IF;
END
$$
"""
    )


def _create_tables() -> list[str]:
    """建表语句，按外键依赖顺序。"""
    return [
        # ------------------------------------------------------------ 租户与身份
        """
CREATE TABLE tenants (
    tenant_id  text PRIMARY KEY,
    name       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
)
""",
        """
CREATE TABLE principals (
    principal_id text PRIMARY KEY,
    tenant_id    text NOT NULL REFERENCES tenants (tenant_id),
    display_name text NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now()
)
""",
        """
CREATE TABLE projects (
    project_id text PRIMARY KEY,
    tenant_id  text NOT NULL REFERENCES tenants (tenant_id),
    name       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
)
""",
        # 项目授权：决定"谁能访问哪个项目"。这是与「客户端自报」相对的那一侧 ——
        # 归属关系只存在于服务端，任何请求字段都改不了它。
        """
CREATE TABLE project_grants (
    tenant_id    text NOT NULL,
    principal_id text NOT NULL,
    project_id   text NOT NULL REFERENCES projects (project_id),
    granted_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (principal_id, project_id)
)
""",
        # ------------------------------------------------------------ 确认记录
        # 成本上界是**数值**（ceiling_amount），不是一句说明 —— 见 03 号规格 §7。
        """
CREATE TABLE confirmations (
    confirmation_id  text PRIMARY KEY,
    tenant_id        text NOT NULL,
    project_id       text NOT NULL REFERENCES projects (project_id),
    principal_id     text NOT NULL,
    tool_id          text NOT NULL,
    params_hash      text NOT NULL,
    ceiling_dimension text NOT NULL,
    ceiling_amount   bigint NOT NULL CHECK (ceiling_amount >= 0),
    ceiling_note     text NOT NULL DEFAULT '',
    issued_at        timestamptz NOT NULL,
    expires_at       timestamptz NOT NULL,
    consumed_at      timestamptz,
    CHECK (expires_at > issued_at)
)
""",
        # ------------------------------------------------------------ 证据事实
        # append-only：没有 updated_at，应用角色也没有 UPDATE / DELETE 权限。
        """
CREATE TABLE evidence_events (
    seq            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       text NOT NULL UNIQUE,
    tenant_id      text NOT NULL,
    project_id     text NOT NULL REFERENCES projects (project_id),
    kind           text NOT NULL,
    task_id        text NOT NULL,
    contract_id    text,
    mapping_version text,
    graph_version  text NOT NULL,
    occurred_at    timestamptz NOT NULL,
    recorded_at    timestamptz NOT NULL DEFAULT now(),
    payload        jsonb NOT NULL
)
""",
        # ------------------------------------------------------------ 执行意图
        # 幂等键唯一：重复投递靠数据库拦，不靠应用层"记得先查一下"。
        """
CREATE TABLE action_intents (
    logical_action_id text PRIMARY KEY,
    tenant_id         text NOT NULL,
    project_id        text NOT NULL REFERENCES projects (project_id),
    run_id            text NOT NULL,
    node_instance_id  text NOT NULL,
    tool_id           text NOT NULL,
    idempotency_key   text NOT NULL UNIQUE,
    state             text NOT NULL,
    attempts          jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
)
""",
    ]


def _index_statements() -> list[str]:
    return [
        # 按租户 + 到期时间清理过期确认。
        "CREATE INDEX confirmations_expiry_idx ON confirmations (tenant_id, expires_at)",
        # 未消费的确认才可能被占用，部分索引更小。
        "CREATE INDEX confirmations_live_idx ON confirmations (confirmation_id)"
        " WHERE consumed_at IS NULL",
        # 证据按项目 + 时间回放（投影要按顺序读）。
        "CREATE INDEX evidence_events_project_seq_idx ON evidence_events (project_id, seq)",
        # 待对账的执行意图。
        "CREATE INDEX action_intents_state_idx ON action_intents (tenant_id, project_id, state)",
    ]


def _grant_statements() -> list[str]:
    statements: list[str] = [
        # schema 使用权。DDL 权限一律不给 —— 应用角色不该能改表结构。
        "REVOKE ALL ON SCHEMA public FROM PUBLIC",
        f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}",
    ]
    for table in TABLES:
        if table in APPEND_ONLY:
            # append-only 由权限系统保证：应用连"改证据"的能力都没有。
            statements.append(f"GRANT SELECT, INSERT ON {table} TO {APP_ROLE}")
        else:
            statements.append(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {APP_ROLE}")
    # identity 列的序列需要 USAGE 才能 INSERT。
    statements.append(f"GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO {APP_ROLE}")
    return statements


def upgrade() -> None:
    _assert_app_role_exists()

    for statement in _create_tables():
        op.execute(statement)

    for table in TABLES:
        for statement in _rls_statements(table, project_scoped=table in PROJECT_SCOPED):
            op.execute(statement)

    for statement in _index_statements():
        op.execute(statement)

    for statement in _grant_statements():
        op.execute(statement)


def downgrade() -> None:
    for table in TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_isolation ON {table}")
    # 逆序删表，避开外键依赖。
    for table in reversed(TABLES):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
