"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

Migrations in this project are WRITTEN BY HAND, not autogenerated:
the schema doubles as a security carrier (RLS policies, per-table GRANTs,
append-only privileges, CHECK constraints). Autogenerate only sees tables
and columns - it would emit DDL that looks complete while silently dropping
every one of those safeguards. See alembic/env.py for the full reasoning.

(This template is deliberately pure ASCII: alembic reads it using the
locale encoding, which is GBK on a Chinese Windows.)
"""

from __future__ import annotations

import sqlalchemy as sa  # noqa: F401  reserved for future migrations
from alembic import op  # noqa: F401

revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
